package wordingo

import (
	"bytes"
	"errors"
	"fmt"
	"strings"

	"github.com/fabiomarini/wordingo/internal/opc"
	"github.com/fabiomarini/wordingo/internal/wml"
	"github.com/fabiomarini/wordingo/internal/xmlutil"
)

// Table of contents support.
//
// AddTableOfContents emits a real OOXML TOC field
// (` TOC \o "1-N" \h \z \u `) that collects the document's headings,
// and fills the field's cached result with static entries derived from
// the headings already present in the body (see Headings). Word
// refreshes the field when the document is opened (w:updateFields in
// word/settings.xml), producing live page numbers and links; viewers
// that do not refresh fields still show the generated summary.

const (
	// tocDefaultTitle is the heading shown above a generated TOC.
	tocDefaultTitle = "Table of Contents"
	// tocDefaultLevels is the default deepest heading level collected.
	tocDefaultLevels = 3
	// tocFallbackTab is the right-tab position (twips) used when the
	// section page size cannot be determined: Letter width minus 1in
	// margins (12240-1440-1440).
	tocFallbackTab = int64(9360)
	// tocBookmarkPrefix is the bookmark-name prefix Word itself uses
	// for TOC targets.
	tocBookmarkPrefix = "_Toc"
)

// ErrTOCTargetNotFound is returned by InsertTableOfContentsBefore when
// the target paragraph is not part of the document body.
var ErrTOCTargetNotFound = errors.New("wordingo: InsertTableOfContentsBefore: target paragraph not found")

// Heading describes one heading paragraph of the document outline.
type Heading struct {
	// Level is the heading depth, 1 (Heading1) through 9 (Heading9).
	Level int
	// Text is the trimmed text content of the heading paragraph.
	Text string
	// Style is the paragraph style id (e.g. "Heading1"), or "" when the
	// heading was derived from an explicit outline level.
	Style string
}

// TOCOptions configures the table of contents generated by
// AddTableOfContents / InsertTableOfContentsBefore. A nil *TOCOptions
// is equivalent to all defaults.
type TOCOptions struct {
	// Title is the heading shown above the TOC. Empty means the
	// default "Table of Contents".
	Title string
	// Levels is the deepest heading level included (1..9). Values
	// outside the range are clamped. Zero means 3.
	Levels int
	// UpdateOnOpen asks Word to refresh all fields — including the
	// TOC — when the document is opened (w:updateFields in
	// word/settings.xml). nil means true; set to false to leave the
	// document settings untouched.
	UpdateOnOpen *bool
}

// TOC is a handle to a generated table of contents section, returned
// by AddTableOfContents and InsertTableOfContentsBefore.
type TOC struct {
	doc   *Document
	title *Paragraph
}

// Title returns the TOC title paragraph (the field's first paragraph).
func (t *TOC) Title() *Paragraph {
	return t.title
}

// normalize returns the effective options for a nil or partially
// populated TOCOptions.
func (o *TOCOptions) normalize() TOCOptions {
	n := TOCOptions{Title: tocDefaultTitle, Levels: tocDefaultLevels}
	if o == nil {
		return n
	}
	if o.Title != "" {
		n.Title = o.Title
	}
	n.Levels = o.Levels
	if n.Levels < 1 {
		n.Levels = 1
	}
	if n.Levels > 9 {
		n.Levels = 9
	}
	n.UpdateOnOpen = o.UpdateOnOpen
	return n
}

// Headings returns the document outline: body paragraphs whose style
// is Heading1..Heading9, or that carry an explicit outline level.
// Headings are returned in document order with their level (1..9) and
// trimmed text. Paragraphs with no heading style or outline level, and
// headings with no text content, are skipped.
func (d *Document) Headings() []Heading {
	if d == nil {
		panic("wordingo: Headings called on nil Document")
	}
	if d.doc == nil || d.doc.Body == nil {
		return nil
	}
	var out []Heading
	for _, p := range d.doc.Body.P {
		level := headingLevel(p)
		if level == 0 {
			continue
		}
		text := strings.TrimSpace(paragraphText(p))
		if text == "" {
			continue
		}
		out = append(out, Heading{Level: level, Text: text, Style: styleOf(p)})
	}
	return out
}

// AddTableOfContents appends a table of contents section at the end of
// the document body. The section consists of a title paragraph
// carrying a TOC field (` TOC \o "1-N" \h \z \u `) followed by one
// entry paragraph per body heading up to the configured depth (see
// TOCOptions). Each entry links to a bookmark placed on its heading,
// so the generated summary is navigable even before Word refreshes the
// field.
//
// Unless TOCOptions.UpdateOnOpen is explicitly false, word/settings.xml
// is patched with w:updateFields so Word repopulates the TOC — with
// live page numbers — when the document is opened.
func (d *Document) AddTableOfContents(opts *TOCOptions) (*TOC, error) {
	if d == nil {
		panic("wordingo: AddTableOfContents called on nil Document")
	}
	if d.doc == nil || d.doc.Body == nil {
		return nil, fmt.Errorf("wordingo: AddTableOfContents: document has no body")
	}
	return d.insertTableOfContentsAt(len(d.doc.Body.P), opts)
}

// InsertTableOfContentsBefore inserts a table of contents section
// (see AddTableOfContents) immediately before target. Returns
// ErrTOCTargetNotFound — after emitting a warning — if target is nil
// or not part of the document body.
func (d *Document) InsertTableOfContentsBefore(target *Paragraph, opts *TOCOptions) (*TOC, error) {
	if d == nil {
		panic("wordingo: InsertTableOfContentsBefore called on nil Document")
	}
	if d.doc == nil || d.doc.Body == nil {
		return nil, fmt.Errorf("wordingo: InsertTableOfContentsBefore: document has no body")
	}
	if target == nil {
		d.warn("wordingo: InsertTableOfContentsBefore: target is nil")
		return nil, ErrTOCTargetNotFound
	}
	for i, p := range d.doc.Body.P {
		if p == target.ct {
			return d.insertTableOfContentsAt(i, opts)
		}
	}
	d.warn("wordingo: InsertTableOfContentsBefore: target paragraph not found")
	return nil, ErrTOCTargetNotFound
}

// insertTableOfContentsAt builds the TOC paragraphs, registers
// bookmarks on the included headings, inserts everything at the pIdx-th
// body paragraph position, and enables field update-on-open unless the
// caller opted out.
func (d *Document) insertTableOfContentsAt(pIdx int, opts *TOCOptions) (*TOC, error) {
	o := opts.normalize()
	paras := d.buildTOC(o)
	d.insertParagraphsAt(pIdx, paras)

	updateOnOpen := o.UpdateOnOpen == nil || *o.UpdateOnOpen
	if updateOnOpen {
		d.enableUpdateFields()
	}
	d.dirty = true
	return &TOC{doc: d, title: &Paragraph{ct: paras[0], doc: d}}, nil
}

// buildTOC constructs the TOC section paragraphs for the current body
// state: a title paragraph with the TOC field, one entry paragraph per
// included heading, and the field's closing character. It also places
// a bookmark on each included heading paragraph so entries can link to
// them. The returned slice is never empty (the first paragraph carries
// the title and field begin).
func (d *Document) buildTOC(o TOCOptions) []*wml.CT_P {
	// Collect the headings that fit the configured depth, together with
	// the underlying paragraphs (for bookmark placement).
	type tocEntry struct {
		heading Heading
		para    *wml.CT_P
	}
	var entries []tocEntry
	for _, p := range d.doc.Body.P {
		level := headingLevel(p)
		if level == 0 || level > o.Levels {
			continue
		}
		text := strings.TrimSpace(paragraphText(p))
		if text == "" {
			continue
		}
		entries = append(entries, tocEntry{
			heading: Heading{Level: level, Text: text, Style: styleOf(p)},
			para:    p,
		})
	}

	// Reserve unique bookmark ids and names for the included headings,
	// then build the anchors the entries will link to.
	nextID, usedNames := d.bookmarkState()
	anchors := make([]string, len(entries))
	for i, e := range entries {
		id, name := nextFreeBookmark(nextID, usedNames)
		nextID = id + 1
		usedNames[name] = true
		anchors[i] = name
		e.para.BookmarkStart = append(e.para.BookmarkStart, &wml.CT_BookmarkStart{ID: &id, Name: &name})
		e.para.BookmarkEnd = append(e.para.BookmarkEnd, &wml.CT_BookmarkEnd{ID: &id})
	}

	instr := fmt.Sprintf(` TOC \o "1-%d" \h \z \u `, o.Levels)
	tabPos := d.tocTabPos()

	paras := []*wml.CT_P{tocTitleParagraph(o.Title, instr)}
	if len(entries) == 0 {
		paras = append(paras, tocHintParagraph(), tocFieldEndParagraph())
		return paras
	}
	for i, e := range entries {
		closeTOC := i == len(entries)-1
		paras = append(paras, tocEntryParagraph(e.heading.Level, e.heading.Text, anchors[i], tabPos, closeTOC))
	}
	return paras
}

// nextFreeBookmark returns an id/name pair for a new bookmark: ids
// count up from nextID, and the derived "_Toc…" name is skipped if it
// is already used elsewhere in the document.
func nextFreeBookmark(nextID int64, usedNames map[string]bool) (int64, string) {
	for {
		id := nextID
		name := fmt.Sprintf("%s%08d", tocBookmarkPrefix, id)
		nextID++
		if usedNames[name] {
			continue
		}
		return id, name
	}
}

// bookmarkState returns the next free bookmark id (one above the
// highest id found in body paragraphs and table cells) and the set of
// bookmark names already in use.
func (d *Document) bookmarkState() (int64, map[string]bool) {
	var maxID int64 = -1
	used := make(map[string]bool)
	visit := func(p *wml.CT_P) {
		for _, bs := range p.BookmarkStart {
			if bs.ID != nil && *bs.ID > maxID {
				maxID = *bs.ID
			}
			if bs.Name != nil {
				used[*bs.Name] = true
			}
		}
	}
	if d.doc != nil && d.doc.Body != nil {
		for _, p := range d.doc.Body.P {
			visit(p)
		}
		for _, tbl := range d.doc.Body.Tbl {
			for _, tr := range tbl.Tr {
				for _, tc := range tr.Tc {
					for _, p := range tc.P {
						visit(p)
					}
				}
			}
		}
	}
	return maxID + 1, used
}

// insertParagraphsAt inserts paras as body paragraphs at the position
// of the pIdx-th paragraph, keeping P and ElemOrder consistent.
func (d *Document) insertParagraphsAt(pIdx int, paras []*wml.CT_P) {
	if len(paras) == 0 {
		return
	}
	body := d.doc.Body
	if len(body.ElemOrder) == 0 {
		d.syncBodyOrder()
	}
	order := body.ElemOrder

	// Insert into P.
	body.P = append(body.P, make([]*wml.CT_P, len(paras))...)
	copy(body.P[pIdx+len(paras):], body.P[pIdx:])
	copy(body.P[pIdx:], paras)

	// Find the ElemOrder index of the pIdx-th paragraph.
	elemIdx := len(order)
	pCount := 0
	for i, e := range order {
		if e == wml.BodyP {
			if pCount == pIdx {
				elemIdx = i
				break
			}
			pCount++
		}
	}
	insert := make([]wml.BodyElemType, len(paras))
	for i := range insert {
		insert[i] = wml.BodyP
	}
	order = append(order, make([]wml.BodyElemType, len(paras))...)
	copy(order[elemIdx+len(paras):], order[elemIdx:])
	copy(order[elemIdx:], insert)
	body.ElemOrder = order
}

// enableUpdateFields patches word/settings.xml with
// w:updateFields w:val="true" so Word refreshes fields on open. It
// warns (never fails the caller) when the part is missing or cannot be
// re-encoded; the TOC field still works via its dirty begin character.
func (d *Document) enableUpdateFields() {
	part, ok := d.pkg.Parts["word/settings.xml"]
	if !ok {
		d.warn("wordingo: table of contents: word/settings.xml missing; Word will not auto-update fields")
		return
	}
	rc, err := part.Open()
	if err != nil {
		d.warn("wordingo: table of contents: open settings: %v", err)
		return
	}
	var settings wml.CT_Settings
	dec := xmlutil.NewSafeDecoder(rc, opc.MaxPartBytes)
	err = dec.Decode(&settings)
	rc.Close()
	if err != nil {
		d.warn("wordingo: table of contents: decode settings: %v", err)
		return
	}
	if settings.UpdateFields != nil {
		return // already enabled
	}
	val := "true"
	settings.UpdateFields = &wml.CT_UpdateFields{Val: &val}

	var buf bytes.Buffer
	buf.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	buf.WriteByte('\n')
	enc := xmlutil.NewEncoder(&buf)
	if err := enc.Encode(&settings); err != nil {
		d.warn("wordingo: table of contents: encode settings: %v", err)
		return
	}
	if err := enc.Flush(); err != nil {
		d.warn("wordingo: table of contents: flush settings: %v", err)
		return
	}
	d.pkg.MarkModified("word/settings.xml", buf.Bytes())
}

// tocTabPos returns the right-edge tab position (twips) for TOC
// entries, derived from the document section's page width minus
// margins. Falls back to tocFallbackTab when unknown.
func (d *Document) tocTabPos() int64 {
	if d.doc != nil && d.doc.Body != nil && d.doc.Body.SectPr != nil {
		sp := d.doc.Body.SectPr
		if sp.PgSz != nil && sp.PgSz.W != nil && sp.PgMar != nil {
			left, right := int64(0), int64(0)
			if sp.PgMar.Left != nil {
				left = *sp.PgMar.Left
			}
			if sp.PgMar.Right != nil {
				right = *sp.PgMar.Right
			}
			if *sp.PgSz.W > left+right {
				return *sp.PgSz.W - left - right
			}
		}
	}
	return tocFallbackTab
}

// ---- paragraph / run construction helpers ----

// tocTitleRPr is the formatting applied to the TOC title text and
// paragraph mark: bold, 16pt.
func tocTitleRPr() *wml.CT_RPr {
	sz := int64(32)
	return &wml.CT_RPr{B: &wml.CT_OnOff{}, Sz: &wml.CT_Sz{Val: &sz}}
}

// tocNoProofRPr suppresses proofing on TOC entry runs (Word applies
// w:noProof to generated TOC content).
func tocNoProofRPr() *wml.CT_RPr {
	return &wml.CT_RPr{NoProof: &wml.CT_OnOff{}}
}

// tocTitleParagraph builds the first TOC paragraph: field begin
// (dirty), the TOC instruction, field separate, and the cached title
// text.
func tocTitleParagraph(title, instr string) *wml.CT_P {
	before, after := int64(240), int64(120)
	dirty := "true"
	rpr := tocTitleRPr()
	return &wml.CT_P{
		PPr: &wml.CT_PPr{
			Spacing: &wml.CT_Spacing{Before: &before, After: &after},
			RPr:     rpr,
		},
		R: []*wml.CT_R{
			{FldChar: &wml.CT_FldChar{Type: strPtr("begin"), Dirty: &dirty}},
			{InstrText: &wml.CT_InstrText{Value: instr}},
			{FldChar: &wml.CT_FldChar{Type: strPtr("separate")}},
			{RPr: rpr, T: &wml.CT_Text{Value: title}},
		},
	}
}

// tocEntryParagraph builds one TOC entry: a hyperlink to the heading's
// bookmark containing the heading text, the tab, and the PAGEREF field
// for the page number — Word's canonical TOC layout, where the field
// renders after the text. When closeTOC is set, the TOC field's closing
// character is emitted as a direct run after the hyperlink (HyperlinkFirst),
// exactly where Word places it in its own generated TOCs.
func tocEntryParagraph(level int, text, anchor string, tabPos int64, closeTOC bool) *wml.CT_P {
	left := int64(level-1) * 226
	hanging := int64(226)
	zero := int64(0)
	nop := tocNoProofRPr()

	// Hyperlink to the heading bookmark, wrapping the entry content:
	// text, tab, then the PAGEREF field. Keeping the field inside the
	// hyperlink ensures cached viewers render "Heading ..... 0" rather
	// than a leading placeholder before the heading text.
	instr := fmt.Sprintf(" PAGEREF %s \\h ", anchor)
	history := "1"
	hl := &wml.CT_Hyperlink{
		Anchor:  &anchor,
		History: &history,
		R: []*wml.CT_R{
			{RPr: nop, T: &wml.CT_Text{Value: text}},
			{RPr: nop, Tab: &wml.CT_Tab{}},
			{RPr: nop, FldChar: &wml.CT_FldChar{Type: strPtr("begin")}},
			{RPr: nop, InstrText: &wml.CT_InstrText{Value: instr}},
			{RPr: nop, FldChar: &wml.CT_FldChar{Type: strPtr("separate")}},
			{RPr: nop, T: &wml.CT_Text{Value: "0"}},
			{RPr: nop, FldChar: &wml.CT_FldChar{Type: strPtr("end")}},
		},
	}

	p := &wml.CT_P{
		PPr: &wml.CT_PPr{
			Spacing: &wml.CT_Spacing{Before: &zero, After: &zero},
			Ind:     &wml.CT_Ind{Left: &left, Hanging: &hanging},
			Tabs: &wml.CT_Tabs{Tab: []*wml.CT_TabStop{{
				Val:    strPtr("right"),
				Leader: strPtr("dot"),
				Pos:    &tabPos,
			}}},
			RPr: nop,
		},
		Hyperlink: []*wml.CT_Hyperlink{hl},
	}
	if closeTOC {
		// Close the outer TOC field after the entry's hyperlink — the
		// same placement Word uses in its own TOC output.
		p.HyperlinkFirst = true
		p.R = []*wml.CT_R{{FldChar: &wml.CT_FldChar{Type: strPtr("end")}}}
	}
	return p
}

// tocHintParagraph is the cached content shown when the document has no
// headings: a hint inside the field, replaced by Word on update.
func tocHintParagraph() *wml.CT_P {
	italic := &wml.CT_RPr{I: &wml.CT_OnOff{}}
	return &wml.CT_P{
		R: []*wml.CT_R{{
			RPr: italic,
			T:   &wml.CT_Text{Value: "(No headings found — add Heading styles to populate the table of contents.)"},
		}},
	}
}

// tocFieldEndParagraph closes the TOC field in its own paragraph. Used
// only when the TOC has no entries; otherwise the closing character is
// appended inside the last entry's hyperlink.
func tocFieldEndParagraph() *wml.CT_P {
	return &wml.CT_P{
		R: []*wml.CT_R{{FldChar: &wml.CT_FldChar{Type: strPtr("end")}}},
	}
}

// ---- heading detection helpers ----

// headingLevel returns the heading depth (1..9) of p, or 0 when p is
// not a heading. Style-based headings (Heading1..Heading9) take
// precedence; otherwise an explicit outline level (0..8) maps to
// level+1, matching Word's \o / \u TOC switches.
func headingLevel(p *wml.CT_P) int {
	if p == nil || p.PPr == nil {
		return 0
	}
	if p.PPr.PStyle != nil && p.PPr.PStyle.Val != nil {
		style := *p.PPr.PStyle.Val
		if len(style) == 8 && strings.HasPrefix(style, "Heading") {
			if dig := style[7]; dig >= '1' && dig <= '9' {
				return int(dig - '0')
			}
		}
	}
	if p.PPr.OutlineLvl != nil && p.PPr.OutlineLvl.Val != nil {
		lvl := *p.PPr.OutlineLvl.Val
		if lvl >= 0 && lvl <= 8 {
			return int(lvl) + 1
		}
	}
	return 0
}

// styleOf returns the paragraph style id of p, or "".
func styleOf(p *wml.CT_P) string {
	if p.PPr != nil && p.PPr.PStyle != nil && p.PPr.PStyle.Val != nil {
		return *p.PPr.PStyle.Val
	}
	return ""
}
